export const FETCH_COIN_LIST = 'FETCH_COIN_LIST';
export const FETCH_COIN_LIST_SUCCESS = 'FETCH_COIN_LIST_SUCCESS';
export const FETCH_COIN_LIST_FAILURE = 'FETCH_COIN_LIST_FAILURE';

export const FETCH_COIN_DETAIL = 'FETCH_COIN_DETAIL';
export const FETCH_COIN_DETAIL_SUCCESS = 'FETCH_COIN_DETAIL_SUCCESS';
export const FETCH_COIN_DETAIL_FAILURE = 'FETCH_COIN_DETAIL_FAILURE';

export const CLEAR_COIN_DETAIL = 'CLEAR_COIN_DETAIL';
